### ISSUE TITLE
Creation date of the draft Conventions document

### ISSUE THREAD

**Issue by larsbarring** [cf-convention/cf-conventions#457]
Currently the creation date of the draft version of the Conventions document is the same as the recentmost released version e.g. today the draft version of CF-1.11 is "version 1.11 draft, 31 August, 2022", even though a PR was merged earlier today.

I imagine that it would be possible to somewhere in the document build process dynamically assign the correct date. But I afraid that the technical aspects for making this happen is out of my reach.

**Comment by JonathanGregory** [comment]
I suppose that a simple fix for that is simply to delete the date in the working version. It can be replaced with some obvious placeholder, to be filled in when a new release is made. Would that be better?

**Comment by erget** [comment]
Yes, that could work. Alternatively, we could have a date that is a placeholder in the AsciiDoc and gets turned into a date during build. I think this question is mostly for those responsible for the building, what they prefer.

**Comment by larsbarring** [comment]
I have played around with this and will shortly create a pull request. In addition to minor changes to the AsciiDoc file, the github workflow for creating the documents have to be slightly modified (details in the PR).

**Comment by davidhassell** [comment]
Hi Lars,

This looks good to me. I have tested it on my local build, and it looks fine for both HTML and PDF documents.

Might I suggest creating an environment variable for the resolved date that can be used in both HTML and PDF build commands? E.g.
```  
    - name: Set draft date-time formatting
      if: github.event_name != 'release'
      run: |
        echo "docprodtime=-a docprodtime=$(date -u '+%d&#160;%B,&#160;%Y')" >> "$GITHUB_ENV"
    - name: Set "final" tag and date-time formatting
      if: github.event_name == 'release'
      run: |
        echo "FINAL_TAG=-a final" >> "$GITHUB_ENV"
    # Build cf-conventions.html using the Analog-inc asciidoctor-action
    - name: Build cf-conventions.html
      uses: Analog-inc/asciidoctor-action@v1.2
      with:
        shellcommand: 'asciidoctor --verbose ${FINAL_TAG} ${docprodtime} cf-conventions.adoc -D conventions_build; cp -r images conventions_build'
    # Build cf-conventions.pdf using the Analog-inc asciidoctor-action
    - name: Build cf-conventions.pdf
      uses: Analog-inc/asciidoctor-action@v1.2
      with:
        shellcommand: 'asciidoctor-pdf --verbose ${FINAL_TAG} -a docprodtime="$(date -u ${DATE_FMT})" -d book -a pdf-theme=default-theme-CF-version.yml --trace cf-conventions.adoc -D conventions_build'
    # Upload artifact containing cf-convent
```
